### ISSUE TITLE
Why did you implement some syscalls / functions in glibc

### ISSUE THREAD

**Issue by y3n11** [elfmaster/skeksi_virus#2]
Hi,

I'm confused why do you implement some syscalls / functions

Thanks !!

**Comment by odzhan** [comment]
Because the code has to be position independent in memory?

**Comment by y3n11** [comment]
what does it mean ?

**Comment by ghost** [comment]
may be he want to say"The executed code is independent and should not call any DLL file on the system." 

yeah?

**Comment by elfmaster** [comment]
Yes The code must maintain position independence so that it can execute with inside of another executable and therefore it has no linking to shared libraries. All viruses make direct calls into the system calls via asm.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
