### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by ruchirmehta07** [elfmaster/skeksi_virus#6]
It does infect the target file but the infected target file gives segmentation fault upon execution.

**Comment by elfmaster** [comment]
I don’t believe it works on binaries with more than two load segments. The
virus was released before the ld separate-code feature came out.

**Comment by ruchirmehta07** [comment]
Yippee!! that indeed worked out well.
I used `gcc -Wall -g -no-pie -z noseparate-code ./target.c -o ./target.elf`
for the virus I used, `gcc -w -g -static -N -O0 -D INFECT_PLTGOT  -fno-stack-protector -nostdlib -fpic virus.c -o virus.elf`
